from datetime import timezone

from roomdoo_locks_base import LockCodeDeletionError, LockError

from odoo import fields, models


class LockCode(models.Model):
    _name = "lock.code"
    _description = "Lock Code"
    _rec_name = "pin"

    pin = fields.Char(
        help="PIN code the guest types on the keypad. Generated by the vendor "
        "library, may change after a modify.",
    )
    vendor_id = fields.Many2one(
        comodel_name="lock.vendor",
        string="Vendor",
        required=True,
        ondelete="restrict",
    )
    vendor_code_id = fields.Char(
        string="Vendor Code ID",
        help="Identifier returned by the vendor API. Required to modify or "
        "remove the code on the lock.",
    )
    reservation_id = fields.Many2one(
        comodel_name="pms.reservation",
        string="Reservation",
        ondelete="cascade",
        index=True,
    )
    room_id = fields.Many2one(
        comodel_name="pms.room",
        string="Room",
        required=True,
        ondelete="cascade",
        index=True,
        help="Room whose lock this code belongs to.",
    )
    date_from = fields.Datetime(required=True)
    date_to = fields.Datetime(required=True)
    state = fields.Selection(
        selection=[
            ("pending", "Pending"),
            ("active", "Active"),
            ("failed", "Failed"),
            ("expired", "Expired"),
            ("cancelled", "Cancelled"),
        ],
        default="pending",
        required=True,
    )
    active = fields.Boolean(default=True)

    @staticmethod
    def _to_utc(dt):
        """Odoo stores naive UTC datetimes; the library requires UTC aware."""
        return dt.replace(tzinfo=timezone.utc)

    @staticmethod
    def _to_naive(dt):
        """Strip tzinfo from an aware UTC datetime for Odoo storage."""
        return dt.astimezone(timezone.utc).replace(tzinfo=None)

    def _apply_code_result(self, result):
        self.ensure_one()
        self.write(
            {
                "vendor_code_id": result.code_id,
                "pin": result.pin,
                "date_from": self._to_naive(result.starts_at),
                "date_to": self._to_naive(result.ends_at),
            }
        )

    def _sync_create(self):
        self.ensure_one()
        connector = self.vendor_id.get_connector()
        try:
            result = connector.create_code(
                lock_id=self.room_id.lock_device_id,
                starts_at=self._to_utc(self.date_from),
                ends_at=self._to_utc(self.date_to),
            )
        except LockError:
            self.state = "failed"
            raise
        self._apply_code_result(result)
        self.state = "active"

    def _sync_modify(self):
        self.ensure_one()
        connector = self.vendor_id.get_connector()
        try:
            result = connector.modify_code(
                lock_id=self.room_id.lock_device_id,
                code_id=self.vendor_code_id,
                starts_at=self._to_utc(self.date_from),
                ends_at=self._to_utc(self.date_to),
            )
        except LockCodeDeletionError as exc:
            self._apply_code_result(exc.new_result)
            self.with_delay()._retry_invalidate(exc.old_code_id)
            return
        except LockError:
            self.state = "failed"
            raise
        self._apply_code_result(result)

    def _sync_remove(self):
        self.ensure_one()
        connector = self.vendor_id.get_connector()
        try:
            connector.invalidate_code(
                lock_id=self.room_id.lock_device_id,
                code_id=self.vendor_code_id,
            )
        except LockError:
            self.state = "failed"
            raise
        self.state = "cancelled"

    def _retry_invalidate(self, code_id):
        """Retry invalidation of an orphan vendor code_id after a modify
        that created the new one but failed to remove the old one."""
        self.ensure_one()
        connector = self.vendor_id.get_connector()
        connector.invalidate_code(
            lock_id=self.room_id.lock_device_id,
            code_id=code_id,
        )
