{
    "name": "PMS BookAI Integration",
    "summary": """
        WhatsApp notifications via BookAI API for PMS
    """,
    "version": "16.0.5.2.0",
    "category": "PMS Management",
    "author": "Commitsun",
    "website": "https://github.com/commitsun/roomdoo-modules",
    "license": "AGPL-3",
    "depends": [
        "pms_notifications",
        "pms",
        "pms_fastapi",
        "phone_validation",
    ],
    "external_dependencies": {
        "python": ["phonenumbers", "whatsapp_formatter"],
    },
    "data": [
        "security/bookai_security.xml",
        "security/ir.model.access.csv",
        "views/pms_notification_template_views.xml",
        "views/pms_notification_log_views.xml",
        "views/pms_property_views.xml",
        "views/res_partner_views.xml",
        "views/llm_account_views.xml",
        "views/agent_views.xml",
        "views/kb_document_views.xml",
        "views/agent_usage_views.xml",
        "views/agent_audit_log_views.xml",
        "views/bookai_tool_views.xml",
        "views/bookai_mcp_server_views.xml",
        "views/bookai_wa_account_views.xml",
        "views/bookai_execution_views.xml",
        "wizards/bookai_register_wizard_views.xml",
        "wizards/pms_notification_manual_send_wizard_views.xml",
        "views/res_config_settings_views.xml",
        "views/menu.xml",
        "data/config_data.xml",
        "data/bookai_agents_data.xml",
        "data/bookai_cron.xml",
        "data/pms_notification_template_bookai_whatsapp.xml",
        "data/pms_property_notification_rules_bookai_whatsapp.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
